
services:
  keycloak-mysql:
    container_name: keycloak-ecom
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carenode
      MYSQL_USER: carenode
      MYSQL_PASSWORD: root
    volumes:
      - ./volume-dat/mysql_keycloak_data:/var/lib/mysql
    ports:
      - "4306:3306"

  redis:
    image: redis:7-alpine
    container_name: carenode-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "900", "1", "--save", "300", "10", "--appendonly", "yes"]

volumes:
  redis_data: